export enum AlertType {
  LOW_STOCK = 'LOW_STOCK',
  EXPIRING_SOON = 'EXPIRING_SOON',
  SALES_ANOMALY = 'SALES_ANOMALY',
  COST_ANOMALY = 'COST_ANOMALY',
  STOCK_DEDUCTION_FAILED = 'STOCK_DEDUCTION_FAILED',
}

export enum AIModel {
  HAIKU = 'HAIKU',
  SONNET = 'SONNET',
}

export enum OnboardingStep {
  GREETING = 'GREETING',
  MENU_REVIEW = 'MENU_REVIEW',
  RECIPE_LOOP = 'RECIPE_LOOP',
  STOCK_SETUP = 'STOCK_SETUP',
  COMPLETE = 'COMPLETE',
}
